From  mcr.microsoft.com/dotnet/core/sdk:2.2 as build
WORKDIR /app

COPY . ./
WORKDIR /app
RUN donet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 as runtime
WORKDIR /app
COPY --from=build /app/out ./
ENTRYPOINT ["dotnet","Ron.XUnitTest"]